### ISSUE TITLE
Member resets password

### ISSUE THREAD

**Issue by rkim00** [chicago-tool-library/circulate#109]
As a member, I want to be able to reset my password if I forget it. Use whatever standard Forget Password scheme exists on Babywearing or similar sites. Maybe once you get it working 80%, show to Jim or Richard to discuss the flow.

See babywearing repo for code to reuse.

RK note: There's also some forgot password in the app already? Not sure what it's hooked up to... might be for admins only. https://app.chicagotoollibrary.org/users/password/new

See [Member portal mock-ups](https://drive.google.com/file/d/172gIc-yOgd-yAxbv4_qnVnC0JwMqacXo/view).

Possibly we get this entirely for free??

**Comment by avinashupadhya99** [comment]
I noticed that there is no confirmation after sending a reset password for admins from [https://app.chicagotoollibrary.org/users/password/new](https://app.chicagotoollibrary.org/users/password/new). Probably worth a new issue for this.
