### ISSUE TITLE
Disable online payments using Library setting

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#1146]
CTL was affected by the recent Square outage. To prepare for that happening again, it would be nice to wire up the `Library.allow_payments` setting so that users aren't able to attempt online payments when the setting is disabled.

This setting is edited via the admin page at http://localhost:3000/admin/manage_features.

When `allow_payments` is false, we'd like to hide the online payment option in the signup flow.

**Comment by charlorr** [comment]
Hi, it looks like this was implemented in [this PR](https://github.com/chicago-tool-library/circulate/pull/803). 

From my testing, it looks like the following works as described in this story: 
* When `Enable Payments` box is unchecked, the payments step in signup and renewal is skipped.

However, there is a reference to making payments on the renewals page even when payments were disabled by the library. I've conditionally excluded that reference to payments in this PR: #1158. 

Please let me know if there is another change that should be made to complete this story.

**Comment by jim** [comment]
Oh nice, it looks like you're right. I was expecting to see logic on the payments page, but it does make sense that it was just skipped entirely. Thanks for doing the digging to get to the bottom of this one!

**Comment by jim** [comment]
Fixed by #1158!
