### ISSUE TITLE
Text message reminders

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#1172]
The app currently only send email notifications. Some members don't use email heavily or would prefer to get text notifications instead. Doing this would involve using an API (such as Twilio) to send text messages in place or or in addition to emails.

Questions
1. Which emails should be texts? Are some (like the welcome email) only emails, while the reminders are text messages?
2. There are checkboxes on the user profile page where they can choose a type of communication. These are unused since the app only supports emails currently, but do we want to keep these? Can someone uncheck both boxes? 
3. What options are there for APIs and providers? What will it cost to start sending text messages?
4. In addition to sending messages, so we need to implement support for replies (for example, to disable texts) as a part of this work?

**Comment by phinze** [comment]
Text messages are online! Plenty of enhancements we can do from here, but calling this one done!
