### ISSUE TITLE
Upgrade JavaScript dependencies

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#1219]
We have a handful of JS dependencies that are out of date (see [the open Dependabot PRs](https://github.com/chicago-tool-library/circulate/pulls?q=is%3Apr+is%3Aopen+label%3AJavaScript)). We can likely bump all of these in a single PR.

To be sure that everything is working, it's probably good to click around the app a little bit and then be sure that the system tests are passing.

**Comment by phinze** [comment]
Our dependabot stuff is pretty up to date nowadays so I think we can close this now.
