### ISSUE TITLE
Appointment emails say "new appointment scheduled" when an appointment is modified

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#1220]
When someone edits an appointment, the email that we send makes it sound like a new appointment was scheduled. We should update the email we send to say "an appointment was updated" instead of "new appointment scheduled".

You can view the current email if you have the app running locally by going to http://localhost:3000/rails/mailers/member_mailer/appointment_confirmation.

**Comment by jpeace-pro** [comment]
Could I claim this issue?

**Comment by jim** [comment]
@jpeace-pro It's all yours!

**Comment by jpeace-pro** [comment]
Resolved in [#1257](https://github.com/chicago-tool-library/circulate/pull/1257)
