### ISSUE TITLE
Update Borrow Policy numbering logic

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#1223]
- The original numbering system needs to be updated before we run out of numbers in the A range.
- This involves removing some special case logic that's applied to A tools.
- Going forwards, A tools will select the next available number instead of finding on in the range between 1-999.

**Comment by CTLvivek** [comment]
Am I understanding correctly that if the next available numbers are 713 and 4650, it will become A-713 until it gets to A-999 and then it'll just be completely in line with the other numbers?

**Comment by jim** [comment]
The way I planned to implement it is that all tools would adopt the same numbering scheme, which is to be assigned a number that is one greater than the current highest number. So when that change is made, the next A tool in your example would be 4621.

We could try to make it smart enough to preserve three digit A numbers as long as it can if that is important. But at some point we hit the limit and run out, so there will eventually be A tools with four digit numbers anyhow.
