### ISSUE TITLE
Member number has globally unique index but numbers are assigned unique per library tenant

### ISSUE THREAD

**Issue by phinze** [chicago-tool-library/circulate#1259]
**Describe the bug**

The `Member#assign_number` method is automatically scoped to the current library by `acts_as_tenant`, but there's a globally unique database index on that column. This means that a number can be assigned that's unique for the current library but has a duplicate in the database, resulting in an index violation and a server error. This is not likely to be something that we hit in production, but it's an issue with the multi-tenancy code that we should fix.

**To Reproduce**
1. In a development server, log in as `admin@example.com`
2. Go to `new_member@example.com` in the admin
3. Click `Verify Info` and complete the verification screen

**Expected behavior**
Verification completes, member number is assigned.

**Observed behavior**
Unique index violation.

**Screenshots**
![2024-01-27 at 14 19 16@2x](https://github.com/chicago-tool-library/circulate/assets/37534/f91425ce-fc8b-4f2c-975a-e976c4e02298)

**Additional context**

 * In [this commit](https://github.com/chicago-tool-library/circulate/commit/e7ae1792237af871992090a0e324a167e29b66ae) member numbers were scoped to be per-library-tenant.
 * However, there's still a [globally unique index on member number column](https://github.com/chicago-tool-library/circulate/blob/f68289725689732c4a608f03241c125ac551b3af/db/schema.rb#L443).
 * This should be changed to be a unique index on the combination of library_id and number.

**Comment by jim** [comment]
@jpeace-pro I inadvertently fixed this while addressing a different issue in #1415!
