### ISSUE TITLE
Improve appointments table on mobile devices

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#1290]
There are many issues with the current view. To start with, we can do the following:

* Add item number to the table
* Collapse the note column on small screens, and replace it with a button that can be pressed to show the notes

Also, feel free to make other improvements that you think help us solve this usability problem!

**Comment by mdecelle** [comment]
Working off this slide for starters: https://docs.google.com/presentation/d/16oKmM-0XEf-AmHAV1dwh7IjohHx4wZgvKe4xpBr8PwI/edit#slide=id.g2b35a3e9cda_0_14
