### ISSUE TITLE
As a user, I would like a Renew All Loaned Items Button

### ISSUE THREAD

**Issue by jpeace-pro** [chicago-tool-library/circulate#1311]
**Is your feature request related to a problem? Please describe.**
When I borrow many items at a time and need to renew all of them, I have to press Renew Loan for each individual item. This can be tedious.

**Describe the solution you'd like**
I'd like to renew all items I have on loan in batch with one "Renew All" button.

**Describe alternatives you've considered**
Borrow fewer items. 

**Additional context**
Maybe items get grouped by return date and you can renew them in groups per date of extension period. I.e. I have 3 items due 12/4 and 4 items due 12/7. I can hit renew all for all items on 12/4 and renew all for all items on 12/7 separately.

**Comment by phinze** [comment]
Looks like Admins can do this so we'll duplicate the behavior for members: https://github.com/chicago-tool-library/circulate/blob/da11149a38787137d484a68a9903184c85535b9c/app/views/admin/members/show.html.erb#L50-L52
