### ISSUE TITLE
As a user, I am getting routed to the wrong page after renewals

### ISSUE THREAD

**Issue by jpeace-pro** [chicago-tool-library/circulate#1312]
**Describe the bug**
On renewing loaned items, if an item is allowed to be renewed without librarian approval, I get routed to a different page instead of back to the loaned items. If I want to renew another item after renewing one of these types of items, I have to reroute myself back to the loaned items page.

**To Reproduce**
1. Go to 'Loans'
2. Click on 'Renew Loan' on an item that does not require librarian approval
3. See routing error

**Expected behavior**
I am rerouted to the account/loans page. Not the account page.

**Screenshots**
This is where I'm being routed:
![image](https://github.com/chicago-tool-library/circulate/assets/25113003/76f7f4bd-a18f-4269-bfe4-ca83a8466339)
This is where I want to be routed:
![image](https://github.com/chicago-tool-library/circulate/assets/25113003/d2313c2d-e9c8-41dd-a89f-386b2b11b650)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 121.0.6167.141

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jim** [comment]
Good call, it would be great to improve this interaction.
