### ISSUE TITLE
Require email confirmation before borrowing items

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#1370]
We have an issue where we end up with invalid email addresses for members.

When folks sign up online, we show them a confirmation page, so we'll use that as the starting point to begin confirming member email addresses.

* Add a banner to this page that says to check their email for a confirmation link (and to click that link).
* Send the confirmation link via email when creating the user (Devise should be able to do this automatically).
* We'll need to show a notice at the top of every page of the member account portal that reminds folks to confirm their email address (and optionally re-send the email if needed).

**Comment by mdecelle** [comment]
The feature to implement is part of https://github.com/heartcombo/devise - they call it "confirmable"
