### ISSUE TITLE
Hold list order modifications don't take effect

### ISSUE THREAD

**Issue by CTLvivek** [chicago-tool-library/circulate#1427]
**Describe the bug**
In the admin view, when I adjust the order of the holds it will show that it's changed but if the page is refreshed or viewed anew from somewhere else, the holds are shown as reverted to their original sequence.

**To Reproduce**
1. Go to 'C-1849' in the admin view.
2. Click on 'Keith' in 4th position and move them to 2nd position on the holds list.
3. Refresh the page or look at the same page from another window/tab.
4. See error with Keith reverting back to 4th position.

**Expected behavior**
The hold should update and actually reflect the desired change.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome

**Additional context**
This obviously isn't super urgent because we have not used the feature to date.  Also, I have a question about what happens if someone is moved into first position in this manner. Will it send out a notification email?  Obviously the original 1st in line will have received an email which we won't be able to retract.

**Comment by phinze** [comment]
- It looks like the error we're seeing here is `InvalidAuthenticityToken` - I'm wondering if it has something to do with a change associated with the turbo upgrade. 🔍
