### ISSUE TITLE
When completing appointment, it does not pop down to the completed list

### ISSUE THREAD

**Issue by phinze** [chicago-tool-library/circulate#1438]
**Describe the bug**

According to @CTLvivek, the appointments list complete button used to pop the row down to the completed list right away, and now it only dims the row, but does not move it until reload.

**To Reproduce**
1. As an admin, go to the appointments list for a day with appointments
2. Click "complete"

**Expected behavior**
Appointment row pops down to completed appointments list lower on the page.

**Observed behavior**
Appointment row only dims, does not pop down until reload.

**Additional context**

I can't find any code that would cause the row to travel to the other list... I'm wondering if the previous observed behavior was due to the pre-turbo/tubolinks full page reload? Question to investigate: how long ago was the appointments list non-turbolinks-enahanced?

**Comment by jim** [comment]
I am also suspicious of the turbolinks upgrades/refactors breaking this.

**Comment by jim** [comment]
Ah yes, there was code to do this: https://github.com/chicago-tool-library/circulate/commit/dbf998327f4e471860c1c94ee357c3fb5f6cf687

I will see about putting that back.
