### ISSUE TITLE
Consolidate bin/setup and bin/reset

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#1487]
We have both `bin/reset` and `bin/setup` scripts. They are mostly the same, and the difference between then (as when to use each one) is not obvious.

Let's combine these into a single script, `bin/setup`. I think we can mostly just use what's in `bin/reset` for this, but it's worth making sure that it works when there isn't yet a database, etc.

**Comment by phinze** [comment]
Good idea! An idempotent bin/setup that's safe to run whenever would be a good QoL improvement.
