### ISSUE TITLE
"Item viewed" ahoy event fires every time you hover over an item

### ISSUE THREAD

**Issue by djcunningham0** [chicago-tool-library/circulate#1581]
**Describe the bug**
The "Item Viewed" event fires every time you hover over an item, e.g., in search results.

**To Reproduce**
Follow these steps in the dev app (or in the production app if you have access to query the production database).

* Search for something in the search bar.
* Hover over the item description hyperlinks or images for a few items.
* Query the `ahoy_events` table (e.g., `select * from ahoy_events order by time desc limit 20;`) and note that there is one "Item Viewed" event for each hover that you performed.

**Expected behavior**
I suspect this was not the intended functionality, and that the events are supposed to fire each time the user clicks on an item to view its page.

**Screenshots**
Here's an example where I searched for "saw" and then hovered over a bunch of the results. Note the large number of "Item Viewed" events in rapid succession.

![image](https://github.com/chicago-tool-library/circulate/assets/38900370/698e74db-60f3-4ca2-a3ef-6d3a5ed04e13)

**Additional context**
Here's where the "Item Viewed" event gets fired in the code.

https://github.com/chicago-tool-library/circulate/blob/0bd00cf74145cb707704e1e2aa1398f943f7e1b7/app/controllers/items_controller.rb#L27-L38

**Comment by djcunningham0** [comment]
@phinze Can you confirm the expected behavior? Any idea why the events are firing like this?

**Comment by djcunningham0** [comment]
The same issue happens with the "Searched" event when you hover over any of the "sort by options" or any of the categories in the left sidebar.

Basically we fire an event any time you hover over a link that would bring you to `/items/...` or `/items?query=...`

**Comment by djcunningham0** [comment]
Inspecting the network traffic, it looks like we're sending a GET request every time the user hovers over any link in the application. Is that expected?

**Comment by phinze** [comment]
That's some surprising behavior to me! Digging in to see what's happening 🔍

**Comment by phinze** [comment]
Well whaddya know [the Turbo framework started doing this by default as of v8](https://turbo.hotwired.dev/handbook/drive#prefetching-links-on-hover), which means [we've been doing this since February](https://github.com/chicago-tool-library/circulate/pull/1323). I think it's a bit too heavy of a server load vs user benefit trade off for us so I'm going to propose we turn it off globally.
