### ISSUE TITLE
Require staff to create a maintenance ticket to set an item's status to  "in maintenance "

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#1743]
1. Disable the "In Maintenance" option on the item edit form.
2. Add something to the hint text for that field that links to the page to create a maintenance ticket. "To set this item to be in maintenance, create a ticket."

![Image](https://github.com/user-attachments/assets/36cf2d31-6547-4ae5-94b1-8688b48a8c82)

**Comment by crismali** [comment]
@jim 

If I remember correctly, you mentioned that creating a ticket should put an item into maintenance. Should that behavior be added as part of this? Locally I can create a ticket and it doesn't impact the status of the item.

**Comment by jim** [comment]
@crismali Yes, that would be great! I misremembered that we already had the app automatically putting items into maintenance.

**Comment by jim** [comment]
Fixed by #1755 .
