### ISSUE TITLE
Send Email to Member when they are #1 in Hold List

### ISSUE THREAD

**Issue by sboligitz** [chicago-tool-library/circulate#209]
As a CTL Member, I want to receive an email notification when I am in the #1 spot on the Hold list so that I know that I can now schedule an appointment to pick up my tool

- Should shoot an email to the Member when they are #1 in the Hold list
- Use email address we have on file
- Use email template --> NEED TO DISCUSS / FORMAT

**Comment by italomatos** [comment]
@sboligitz is there some email template to this issue?

**Comment by rkim00** [comment]
Hi @italomatos , we don't have an e-mail for this yet. I can get you something soon though if you want to work on this one.
