### ISSUE TITLE
Silence log messages

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#433]
**Describe the bug**
Every time a `rails` command is run (e.g. `rails test`), the following lines are printed:

```
I, [2021-01-26T13:07:08.916007 #61]  INFO -- : Adding #<IPAddr: IPv4:172.25.0.0/255.255.255.0> to config.web_console.permissions
I, [2021-01-26T13:07:09.611612 #61]  INFO -- Mjml: Using mjml binary at /usr/src/app/node_modules/.bin/mjml
```

This is helpful in some situations (like when the server starts), but it's just noise when using the Rails CLI.

**To Reproduce**
1. Run `rails db:migrate` or any other `rails` command.

**Comment by h-m-m** [comment]
Is this still an issue? I was unable to reproduce it locally

**Comment by jim** [comment]
No longer an issue.
