### ISSUE TITLE
Librarian view: Item image rotation issue

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#518]
**Describe the bug**

On the Librarian view: The image for [this item](https://app.chicagotoollibrary.org/admin/items/13) on the live site appears correctly on the edit photo page, but not on the item page or item index (e.g., https://app.chicagotoollibrary.org/items/13), where it's rotated 90 degrees. See screenshots below.

We're storing a rotation value in the database, but the output to the user is wrong. I'm assuming that something is happening with Imagekit- perhaps it is detecting some metadata in the original image and auto-rotating it?

Librarian view
![Screenshot 2021-08-31 193801](https://user-images.githubusercontent.com/3331/131593416-5a133a8f-81bc-476f-95c1-6a808d918607.png)

(User-facing) Item page view
![Screenshot 2021-08-31 193733](https://user-images.githubusercontent.com/3331/131593422-28ef1505-b51f-4079-9899-b9964aa13c4f.png)

**Comment by pjsier** [comment]
Could you post a link to the image directly so it can be downloaded? I have a feeling it would be fixed by adding this CSS, but I can't test it

```css
img {
  image-orientation: from-image;
}
```

**Comment by jim** [comment]
Here's the file as we serve it: https://ik.imagekit.io/sac4wk7wt3/d2tx8o0qr4z10i1idpj3vmpn4gnm?tr=w-600,h-600,c-at_max,rt-270

And here's the actual image: 
![d2tx8o0qr4z10i1idpj3vmpn4gnm](https://user-images.githubusercontent.com/3331/132051534-589860c0-55b8-4d28-9fdb-a8cc1d1ae4c8.jpg)


We have some code that's supposed to store a user-provided rotation and apply it- that's where the `rt-270` comes from. I don't know if the issue is that the rotation in the editing UI is broken, or if the way we display the file through ImageKit is the issue.

**Comment by jimnanney** [comment]
Using that link above and changing the rt-270 to rt-0, can't check the prod values that are shored for the url in prod. but it looks like the rotation value is attached to it.

**Comment by phinze** [comment]
This works now since we switched away from ImageKit! https://app.chicagotoollibrary.org/items/13
