### ISSUE TITLE
User view: Items show up as checked out on appointment page when the hold has expired.

### ISSUE THREAD

**Issue by rkim00** [chicago-tool-library/circulate#639]
This may have been fixed... see if you can reproduce.

Currently on pages like 
https://circulate-staging.herokuapp.com/account/appointments/new , items with expired holds display as options to be picked up (although the item shows up as checked out). 

Expected behavior is that when the hold has expired, the item should not display on this page.

**Comment by pjsier** [comment]
@rkim00 I tried to reproduce this and I can't in local development. I created a hold, confirmed it showed up on the new new appointments page, and then went into the Rails console and modified the start date to be far enough in the past that it would be expired. When I went back to the new appointments page I didn't see it anymore

**Comment by RachelWyatt** [comment]
@rkim00 I am also unable to reproduce this issue when creating a new hold and then editing the ```started_at``` date to be greater than 7 days in the past.

**Comment by RachelWyatt** [comment]
@rkim00 I am also unable to reproduce this issue when creating a new hold and then editing the ```started_at``` date to be greater than 7 days in the past.
