### ISSUE TITLE
Staff can still put items on hold or check things out when members have overdue items.

### ISSUE THREAD

**Issue by CTLvivek** [chicago-tool-library/circulate#665]

**Comment by CTLvivek** [comment]
I'm assuming this title (originally created by Jim) is the desire to hardcode this policy rule so that it's easier for librarians to follow and enforce. If that's the right understanding, I'd say that at the moment it's better to have the flexibility but I'm sure it'd be fine either way.

**Comment by jim** [comment]
We want to allow staff to check out and put things on hold regardless of if a person has things that are overdue. The system currently doesn’t allow this, and it’s more annoying than helpful.
