### ISSUE TITLE
Lost member address information during renewal(?)

### ISSUE THREAD

**Issue by CTLvivek** [chicago-tool-library/circulate#721]
**Describe the bug**
It seems like some member addresses that we used to have are disappearing.  (It's likely fair to assume that all members had an address listed because of another 'bug' that will not let you verify a member unless they have an address on file.)  

We suspect that this data loss is being caused when people are renewing.  In theory, members have an option to update their addresses when they renew so maybe if they don't update and don't re-enter their existing address, then the member's account gets overwritten with a blank. Could be totally unrelated.

**To Reproduce**
Not 100% sure. This is being noticed anecdotally, sorry for the ambiguity. It's a tough issue to parse through and track. 

A specific example includes member #28. They definitely had an address but don't have one currently. Contact Tessa for potential other examples.

**Comment by jim** [comment]
Closing since it's been 2 years, we can reopen if this comes up again.
