### ISSUE TITLE
Librarian: Allow staff to lend individual holds to a member

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#76]
For librarians, on the members' hold page (e.g., https://circulate-staging.herokuapp.com/admin/members/587/holds), add a "Lend" button:

<img width="648" alt="Screen Shot 2020-07-06 at 9 01 44 PM" src="https://user-images.githubusercontent.com/3331/86692611-8c3a7c00-bfcf-11ea-969e-5c557720945b.png">

When clicked, lend only that tool to the member. Redirect to the same holds page.

The hold will disappear, which might be a little disorienting. There is probably an affordance we can use to address this. Ideas welcome!

**Comment by preethinarayan** [comment]
@rkim00 could I pick this up?

**Comment by rkim00** [comment]
Sure, give it a shot! Let me know if you have any questions.

**Comment by rkim00** [comment]
@jim despite the merge, I'm not seeing this in staging. Did this not merge correctly or did we decide not to do this?
