### ISSUE TITLE
Search should only return available items.

### ISSUE THREAD

**Issue by CTLvivek** [chicago-tool-library/circulate#772]
**Describe the bug**
The inventory no longer shows unavailable items when browsing the inventory but if you search for an item, the search can return unavailable items.

**To Reproduce**
1. Go to 'https://app.chicagotoollibrary.org/items'
2. Search for 'foxglove'
3. Item 'A-532' is listed in the search results.

**Expected behavior**
Search should not return items that aren't available.

**Comment by kinduff** [comment]
Happy to take this one @jim

**Comment by shkm** [comment]
@jim is this still an issue? Can't reproduce but perhaps the case above is no longer valid.

**Comment by CTLvivek** [comment]
@shkm, looks like this has been addressed. I can see the unavailable items in the librarian/admin view but they aren't coming up when searching from the public view which was the goal. I didn't do a exhaustive examination but I cross compared against "wildflower", "foxglove" and "circular saw".

**Comment by kinduff** [comment]
I can unassigned since I stale this for a while. Feel free to remove me. Sorry for not providing updates.
