### ISSUE TITLE
Category filters don't filter the items list

### ISSUE THREAD

**Issue by rkim00** [chicago-tool-library/circulate#836]
The category filters in the public items list don't seem to be working. For example, [this page](https://circulate-staging.herokuapp.com/items?category=77) should only show items with the Clamping and Securing category, but it shows many more. Look at the counts being so off between what is shown in the sidebar and what is shown at the top of the list:

![example of filter not working](https://user-images.githubusercontent.com/3331/139459152-babdccb4-1b41-4a89-b480-1890d60625d0.png)

There have been some recent changes to the ItemsController#index method to add availability filtering, so that is probably a good place to start looking for the cause.

**Comment by jim** [comment]
This isn't currently an issue as we rolled back the changes that introduced the problem.
