### ISSUE TITLE
Improve tool embedding metadata

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#867]
**Is your feature request related to a problem? Please describe.**

When someone posts a link to a tool on Facebook/Twitter/etc, it would be nice for there to be a nice preview of the item (with a photo if there is one) that is shown.

**Comment by phinze** [comment]
Some example docs talking about this kind of functionality: https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

Those are Twitter specific but I think there's some Open Graph standard discussed on there that might cover multiple services. Ideally we'd figure out what collection of tags we need so things look decent on the major social media platforms.

**Comment by phinze** [comment]
![2024-07-17 at 17 04 11@2x](https://github.com/user-attachments/assets/05de5d61-741e-41e8-aecb-24c9037511d4)

Looking great! I think we can call this done and open fresh issues for any tweaks we want to make.
