### ISSUE TITLE
Reorganize member navigation

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#889]
**Is your feature request related to a problem? Please describe.**
We're starting to get a lot of links in the main nav for members. We need to have room to add more new links as well.

**Describe the solution you'd like**
Collapse Loans, Holds, and Appointments into a new menu called "Borrowing".
Collapse Membership and Logout into a new menu called "Account".

We want to be sure that these menus are accessible and can be operated with only the keyboard. We have dropdown menus on the admin side that we should be able to use as a template for this work.

**Comment by ktun95** [comment]
Hello! I'd like to work on this issue if that's all right!

**Comment by jim** [comment]
@crismali did this in #1660
