### ISSUE TITLE
Upgrade to Rails 7

### ISSUE THREAD

**Issue by jim** [chicago-tool-library/circulate#975]
A new version of Rails is out! We'd like to upgrade to it this year now that things are looking pretty stable.

There is a guide to this process that we should be able to follow: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0

**Comment by archonic** [comment]
Hi @jim, is this something I could take on? I also volunteer at a tool library and while we don't use circulate, I'm wondering if there's anything I could do to help out :)

**Comment by jim** [comment]
@archonic Sure, if you want to take a stab at it, that would be great!

**Comment by archonic** [comment]
Awesome! It looks like the Dockerfile hasn't been updated and seems to have a permissions error when starting. Do you mind if I bring that into a good state too?

**Comment by jim** [comment]
@archonic Not at all. I don't use it a ton myself, but I know that some folks do and having it fixed up would be appreciated.

I know in the past we used [a wrapper script](https://github.com/chicago-tool-library/circulate/blob/f5d0b3425c3b61e3cd2fc20b4ab113088636ff4d/docker-build.sh) to workaround a permissions issue, perhaps that's not needed anymore?

**Comment by jim** [comment]
I just merged #1134 in case if affects what you're working on 😄

**Comment by archonic** [comment]
@jim All done! Lemme know if it needs any fixing up. I'll be away for a couple weeks after Oct 7th but available after that.

**Comment by jim** [comment]
Fixed by #1178.
